Repository unifiedjs/unified-language-server, pull requests merged in 2022-01, with the labels that each got.

#21 Replace mocks/stubs in tests with LSP
  lib/index.js
  package.json
  test/index.js
  test/lots-of-warnings.js
  test/one-error.js
  test/remark-with-error.js
  test/remark-with-warnings.js
  test/remark.js
  test/test-plugin.js
Labels: 🤞 phase/open

#22 Add support for workspaces
  lib/index.js
  package.json
  readme.md
  test/folder/remark-with-cwd.js
  test/index.js
  test/remark-with-cwd.js
Labels: 🦋 type/enhancement, 🗄 area/interface, 🧒 semver/minor, 🤞 phase/open

#27 Fix workspace initialization
  lib/index.js
  test/index.js
Labels: 🐛 type/bug, 👶 semver/patch, 🤞 phase/open

#28 Add support for vfile message notes
  lib/index.js
  test/index.js
  test/lots-of-warnings.js
Labels: 🦋 type/enhancement, 🧒 semver/minor, 🤞 phase/open
